# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='fecha',
        ),
        migrations.AddField(
            model_name='grado',
            name='cursos',
            field=models.ManyToManyField(through='notas.Pensum', to='notas.Curso'),
        ),
    ]
